# Generated by Django 4.2 on 2023-05-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ucasports", "0002_competition_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="location",
            field=models.CharField(max_length=200),
        ),
    ]
