# Generated by Django 4.2 on 2023-05-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ucasports", "0003_alter_competition_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="description",
            field=models.TextField(default="Competition of a lifetime"),
        ),
    ]
