# Generated by Django 4.2 on 2023-05-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ucasports", "0004_competition_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="description",
            field=models.TextField(),
        ),
    ]
