# Generated by Django 4.2 on 2023-05-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ucasports", "0005_alter_competition_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="status",
            field=models.CharField(
                choices=[("Scheduled", "Scheduled"), ("Finished", "Finished")],
                default="Scheduled",
                max_length=20,
            ),
        ),
    ]
